services:
  - type: web
    name: watersing
    region: singapore
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeployTrigger: commit
    envVars:
      - key: AUTH_KEY
        sync: false
      - key: PORT
        value: "10000"
